Repository ergonode/backend, pull requests merged in 2019-09, with the labels that each got.

#116 Fix multimedia ID generation
  module/multimedia/src/Application/Controller/Api/MultimediaController.php
  module/multimedia/src/Domain/Command/UploadMultimediaCommand.php
  module/multimedia/src/Domain/Entity/MultimediaId.php
Labels: bug

#129 #128 Profile and account log should take into attention the importer
  module/account/src/Persistence/Dbal/Query/DbalLogQuery.php
Labels: bug, users

#134 #133 Product delete
  features/product.feature
  module/product/migrations/Version20180619083830.php
  module/product/src/Application/Controller/Api/ProductController.php
  module/product/src/Domain/Command/DeleteProductCommand.php
  module/product/src/Domain/Event/ProductDeletedEvent.php
  module/product/src/Domain/Repository/ProductRepositoryInterface.php
  module/product/src/Infrastructure/Handler/DeleteProductCommandHandler.php
  module/product/src/Persistence/Dbal/Repository/DbalProductRepository.php
  module/product/src/Resources/translations/log.en.yaml
  module/product/src/Resources/translations/log.pl.yaml
Labels: enhancement

#140 Template wrong validation size position required
  features/designer.feature
  module/designer/src/Application/Form/Transformer/PositionFormDataTransformer.php
  module/designer/src/Application/Form/Transformer/SizeFormDataTransformer.php
  module/designer/src/Application/Form/Type/PositionFormType.php
  module/designer/src/Application/Form/Type/Properties/AttributeElementPropertyType.php
  module/designer/src/Application/Form/Type/SizeFormType.php
Labels: bug

#139 Create boolean data transformer
  module/core/src/Application/Form/DataTransformer/BooleanDataTransformer.php
  module/core/src/Application/Form/Type/BooleanType.php
  module/core/tests/Application/Form/DataTransformer/BooleanDataTransformerTest.php
Labels: enhancement

#152 System attribute (hotfix)
  module/attribute-date/src/Domain/Entity/DateAttribute.php
  module/attribute-date/src/Domain/Factory/DateAttributeFactory.php
  module/attribute-image/src/Domain/Entity/ImageAttribute.php
  module/attribute-image/src/Domain/Factory/ImageAttributeFactory.php
  module/attribute-price/src/Domain/Entity/PriceAttribute.php
  module/attribute-price/src/Domain/Factory/PriceAttributeFactory.php
  module/attribute-unit/src/Domain/Entity/UnitAttribute.php
  module/attribute-unit/src/Domain/Factory/UnitAttributeFactory.php
  module/attribute/migrations/Version20180625083834.php
  module/attribute/src/Domain/Command/CreateAttributeCommand.php
  module/attribute/src/Domain/Entity/AbstractAttribute.php
  module/attribute/src/Domain/Entity/Attribute/AbstractOptionAttribute.php
  module/attribute/src/Domain/Event/Attribute/AttributeCreatedEvent.php
  module/attribute/src/Domain/Event/Attribute/AttributeSystemChangedEvent.php
  module/attribute/src/Domain/Factory/MultiSelectAttributeFactory.php
  module/attribute/src/Domain/Factory/NumericAttributeFactory.php
  module/attribute/src/Domain/Factory/SelectAttributeFactory.php
  module/attribute/src/Domain/Factory/TextAttributeFactory.php
  module/attribute/src/Domain/Factory/TextareaAttributeFactory.php
  module/attribute/src/Persistence/Dbal/Projector/AttributeCreatedEventProjector.php
  module/attribute/src/Persistence/Dbal/Projector/AttributeSystemChangedEventProjector.php
  module/attribute/src/Persistence/Dbal/Query/DbalAttributeGridQuery.php
  module/attribute/src/Persistence/Dbal/Query/DbalAttributeQuery.php
  module/fixture/src/Resources/fixtures/develop/attributes.yaml
  module/fixture/src/Resources/fixtures/develop/translation.yaml
  module/fixture/src/Resources/fixtures/fixture.yaml
  module/grid/src/Column/LabelColumn.php
  module/product/src/Infrastructure/Grid/Builder/ProductGridColumnBuilder.php
  module/workflow/src/Infrastructure/Grid/StatusGrid.php
Labels: enhancement

#153 Product grid column order fix
  module/attribute/src/Persistence/Dbal/Query/DbalAttributeGridQuery.php
  module/attribute/src/Persistence/Dbal/Query/DbalAttributeGroupQuery.php
  module/product/src/Infrastructure/Grid/Builder/ProductGridColumnBuilder.php
Labels: bug

#154 Status grid column order fix
  module/workflow/src/Infrastructure/Grid/StatusGrid.php
Labels: bug

#155 Release 0.4.0 fixes
  features/category-tree.feature
  module/account/src/Infrastructure/Grid/AccountGrid.php
  module/attribute-date/src/Domain/Entity/DateAttribute.php
  module/attribute-date/src/Domain/Factory/DateAttributeFactory.php
  module/attribute-image/src/Domain/Entity/ImageAttribute.php
  module/attribute-image/src/Domain/Factory/ImageAttributeFactory.php
  module/attribute-price/src/Domain/Entity/PriceAttribute.php
  module/attribute-price/src/Domain/Factory/PriceAttributeFactory.php
  module/attribute-unit/src/Domain/Entity/UnitAttribute.php
  module/attribute-unit/src/Domain/Factory/UnitAttributeFactory.php
  module/attribute/migrations/Version20180625083834.php
  module/attribute/src/Domain/Command/CreateAttributeCommand.php
  module/attribute/src/Domain/Entity/AbstractAttribute.php
  module/attribute/src/Domain/Entity/Attribute/AbstractOptionAttribute.php
  module/attribute/src/Domain/Event/Attribute/AttributeCreatedEvent.php
  module/attribute/src/Domain/Event/Attribute/AttributeSystemChangedEvent.php
  module/attribute/src/Domain/Factory/MultiSelectAttributeFactory.php
  module/attribute/src/Domain/Factory/NumericAttributeFactory.php
  module/attribute/src/Domain/Factory/SelectAttributeFactory.php
  module/attribute/src/Domain/Factory/TextAttributeFactory.php
  module/attribute/src/Domain/Factory/TextareaAttributeFactory.php
  module/attribute/src/Persistence/Dbal/Projector/AttributeCreatedEventProjector.php
  module/attribute/src/Persistence/Dbal/Projector/AttributeSystemChangedEventProjector.php
  module/attribute/src/Persistence/Dbal/Query/DbalAttributeGridQuery.php
  module/attribute/src/Persistence/Dbal/Query/DbalAttributeGroupQuery.php
  module/attribute/src/Persistence/Dbal/Query/DbalAttributeQuery.php
  module/category-tree/src/Application/Controller/Api/CategoryTreeController.php
  module/category-tree/src/Application/Model/CategoryTreeUpdateFormModel.php
  module/category-tree/src/Domain/Command/UpdateTreeCommand.php
  module/category-tree/src/Domain/Event/CategoryTreeCategoriesChangedEvent.php
  module/category-tree/tests/Domain/Event/CategoryTreeCategoriesChangedEventTest.php
  module/fixture/src/Resources/fixtures/develop/attributes.yaml
  module/fixture/src/Resources/fixtures/develop/products.yaml
  module/fixture/src/Resources/fixtures/develop/translation.yaml
  module/fixture/src/Resources/fixtures/fixture.yaml
  module/grid/src/Column/BoolColumn.php
  module/grid/src/Column/LabelColumn.php
  module/grid/src/Filter/LabelFilter.php
  module/product/src/Domain/Entity/AbstractProduct.php
  module/product/src/Infrastructure/Grid/Builder/ProductGridColumnBuilder.php
  module/product/src/Persistence/Dbal/DataSet/DbalProductDataSet.php
  module/workflow/src/Domain/Entity/Status.php
  module/workflow/src/Domain/Factory/Decorator/StatusProductFactoryDecorator.php
  module/workflow/src/Domain/Query/StatusQueryInterface.php
  module/workflow/src/Infrastructure/Grid/StatusGrid.php
  module/workflow/src/Persistence/Dbal/Query/DbalStatusQuery.php
  module/workflow/src/Resources/config/services.yml
Labels: bug

#158 Vendor version hotfix
  module/attribute/composer.json
  module/event-sourcing/composer.json
  module/fixture/composer.json
  module/grid/composer.json
  module/migration/composer.json
  module/translation-deepl/composer.json
Labels: bug

#161 Release/v0.5.0 fixes
  module/attribute-date/src/Domain/ValueObject/DateFormat.php
  module/attribute/src/Domain/Factory/MultiSelectAttributeFactory.php
  module/attribute/src/Domain/Factory/SelectAttributeFactory.php
  module/condition/src/Domain/Condition/NumericAttributeValueCondition.php
  module/condition/src/Domain/Condition/TextAttributeValueCondition.php
  module/condition/src/Infrastructure/Builder/Condition/NumericAttributeValueConditionValidatorBuilder.php
  module/condition/src/Infrastructure/Grid/ConditionSetGrid.php
Labels: bug
